In [7]:
import numpy as np

In [8]:
a=np.array([[1,2],[3,4],[5,6]])
c=np.array([1,2])
b=np.array([3,4])

SyntaxError: can't use starred expression here (<ipython-input-18-8a49ade7759b>, line 4)

In [9]:
a.shape[0]

3

In [10]:
a.size

6

In [11]:
(c-b)**2

array([4, 4], dtype=int32)

In [12]:
np.sum((c-b)**2)

8

In [13]:
np.sum((c-b)**2)**(1/2)

2.8284271247461903

In [14]:
X=np.array([[1,2],[3,4],[5,6]])

In [15]:
np.random.choice(X.shape[0], size = 2, replace = False)


array([2, 0])

In [16]:
s= np.random.choice(X.shape[0], size = 2, replace = False)
X[s,:]

array([[5, 6],
       [3, 4]])

In [21]:
kmeans = MyKMeans(n_clusters=2, cluster_senters_ =X[s,:]).classify(X)

IndexError: invalid index to scalar variable.

In [38]:
dist = np.vectorize(lambda x, y : np.sqrt(x**2+y**2))
dist(v,w)

0

In [159]:
c=np.array([1,2,3,2,2,1])
c

array([1, 2, 3, 2, 2, 1])

In [147]:
x=np.array([1,2,23,4,5,5,67])

In [158]:
C=np.array([[0,0],[1,1],[2,2],[3,3],[4,4],[5,5]])
C

array([[0, 0],
       [1, 1],
       [2, 2],
       [3, 3],
       [4, 4],
       [5, 5]])

In [149]:
X = np.array([[1, 2], [1, 4], [1, 0],
              [10, 2], [10, 4], [10, 0]])

array([[23],
       [ 4],
       [ 5],
       [ 5],
       [67]])

In [160]:
C[c]

array([[1, 1],
       [2, 2],
       [3, 3],
       [2, 2],
       [2, 2],
       [1, 1]])

In [166]:
np.sqrt(np.sum((X-C[c])**2,axis=1))

array([1.        , 2.23606798, 3.60555128, 8.        , 8.24621125,
       9.05538514])

In [155]:
np.sqrt(np.sum((X-Y)**2,axis=1))

array([ 10.,   0.,   0.,  20., 300.,   0.])

In [150]:
Y = np.array([[11, 2], [1, 4], [1, 0],
              [10, 22], [310, 4], [10, 0]])

In [144]:
X = np.array([[1, 2], [1, 4], [1, 0],
              [10, 2], [10, 4], [10, 0]])
fit(X)
X

[[10.  4.]
 [ 1.  2.]
 [10.  2.]]
[[ 1.  2.]
 [ 1.  4.]
 [ 1.  0.]
 [10.  2.]
 [10.  4.]
 [10.  0.]] ---------------------







<class 'numpy.ndarray'>
[1 1 1 2 0 2]


array([[ 1,  2],
       [ 1,  4],
       [ 1,  0],
       [10,  2],
       [10,  4],
       [10,  0]])

In [138]:


def fit(X): #중심과 레이블을 계산하여 self.cluster_centers_와 self.labels_에 저장
    n_clusters = 3        # number of clusters
    EPSILON = 0.00001              # EPSILON; stop if the sum of centroid movements <= EPSILON
    max_iter = 10            # maximum number of iterations
    cluster_centers_ = np.zeros(n_clusters)        # means of clusters
    labels_ = None   
    def classify(x,y):
        """return the index of the cluster closest to the input"""
        print()
        #print( min(range(n_clusters),                   key=lambda i: np.sqrt(np.sum((input-cluster_centers_[i])**2))))
        return min(range(n_clusters),
                   key=lambda i: np.sqrt(np.sum(((x,y)-cluster_centers_[i])**2)))
    X = X.astype(float)
    # FILL OUT
    cluster_centers_ = X[np.random.choice(X.shape[0], size = n_clusters, replace = False),:]#randly하게 초기값 선택
    assignments = cluster_centers_ #일단 0으로 꽉채움
    print(cluster_centers_)
    classy = np.vectorize(classify)
    print(X,"---------------------")
    new_assignments = classy(X.T[0],X.T[1])
    print(type(new_assignments))
    print(new_assignments)


In [127]:
X
X.T

array([[ 1,  1,  1, 10, 10, 10],
       [ 2,  4,  0,  2,  4,  0]])

In [110]:
(np.array([1,2])-np.array([2,3]))**2

array([1, 1], dtype=int32)

In [112]:
class MyKMeans:        
    def __init__(self, n_clusters=8, n_init=10, EPSILON=1e-4, max_iter=300,cluster_senters_ =None):
        self.n_clusters = n_clusters        # number of clusters
        self.n_init = n_init                # number of time the k-means algorithm will be run with different centroid seeds.
        self.EPSILON = EPSILON              # EPSILON; stop if the sum of centroid movements <= EPSILON
        self.max_iter = max_iter            # maximum number of iterations
        self.cluster_centers_ =np.zeros(n_clusters)        # means of clusters
        self.labels_ = None                 # X's assignments to clusters
        
    def classify(self, input):
        """return the index of the cluster closest to the input"""
        return min(range(self.n_clusters),
                   key=lambda i: np.sqrt(np.sum((input-self.cluster_centers_[i])**2)))
        
    def fit(self, X): #중심과 레이블을 계산하여 self.cluster_centers_와 self.labels_에 저장
        X = X.astype(float)
        # FILL OUT
        x = np.array(X)
        self.cluster_centers_ = X[np.random.choice(x.shape[0], size = self.n_clusters, replace = False),:]
        assignments = numpy.zeros(x.shape[0])

        for i in range(self.max_iter):
            
            if np.abs(assignments-new_assignments):
                return
            
            assignments = new_assignments
        return self
    def score(self,X):
        

SyntaxError: invalid syntax (<ipython-input-112-c0273792d415>, line 23)

In [167]:
a=np.zeros(5)

In [184]:
np.mean(a,axis=0)

array([2.33333333, 2.33333333])

In [185]:
7/3

2.3333333333333335

In [169]:
a[1]=np.array([2,2,22])

ValueError: setting an array element with a sequence.

In [303]:
a = np.array([[1, 2], [3, 40]])
b = np.array([[7, 8], [9, 10], [11, 12]])

In [304]:
c=np.concatenate((a, b), axis=0)

In [305]:
c

array([[ 1,  2],
       [ 3, 40],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [309]:
a=np.array([1,1])
b=np.array([[2,2],[3,3],[4,4]])

In [313]:
np.sqrt(np.sum((a-b)**2,axis=1))

array([1.41421356, 2.82842712, 4.24264069])

In [314]:
np.argmin(np.sqrt(np.sum((a-b)**2,axis=1)))

0

In [249]:
A=np.array([[1,2],[2,2],[4,3]])
b=np.array([[2,3]])
c=np.array([4,3])

In [253]:
a=np.array([1,2,1])

In [254]:
xx=np.argwhere(a==1)

In [263]:
A[xx]

array([[[1, 2]],

       [[4, 3]]])

In [262]:
A[xx].shape

(2, 1, 2)

In [272]:
lk=np.mean(A[xx],axis=0)
lk

array([[2.5, 2.5]])

In [273]:
np.zeros(2).reshape(1,2)


array([[0., 0.]])

In [280]:
z= np.array([[33331,23333],[2,3],[3,1]])
z

array([[33331, 23333],
       [    2,     3],
       [    3,     1]])

In [283]:
a

(33331, 2, 3)

In [215]:
np.concatenate([a, b],axis=0)

array([[1, 2],
       [2, 2],
       [4, 3],
       [2, 3]])

In [220]:
xx=[]
xx.append(c)
xx
xx.append(c)
xx
np.array(xx)

array([[4, 3],
       [4, 3]])

In [193]:
np.append(NO,b,axis=1)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [192]:
np.concatenate(a,c,axis=1)

TypeError: concatenate() got multiple values for argument 'axis'

In [176]:
c=np.array([3,4])

In [ ]:
random.seed(0) # so you get the same results as me
# random.seed(1)
clusterer = KMeans(3)
clusterer.train(data)
print("3-means:")
print(clusterer.means)
my_clusters = [clusterer.classify(p) for p in data]
colormap = 'bgrcmyk'
my_color = list(map(lambda i: colormap[i], my_clusters))
x, y = zip(*data)
plt.scatter(x, y, color=my_color)
xc, yc = zip(*clusterer.means)
plt.scatter(xc, yc, marker='s')
plt.axis('equal')
plt.show()