In [5]:
import numpy

In [6]:
import numpy as np

oneDim = np.array([1.0,2,3,4,5])
print(oneDim)
print("#Dimensions =", oneDim.ndim) #1차원
print("Dimension =", oneDim.shape)  #
print("Size =", oneDim.size)
print("Array type =", oneDim.dtype)

[1. 2. 3. 4. 5.]
#Dimensions = 1
Dimension = (5,)
Size = 5
Array type = float64


numpy element has only one type like C array

In [7]:
twoDim = np.array([[1,2],[3,4],[5,6],[7,8]])  # a two-dimensional array (matrix)
print(twoDim) 
print("#Dimensions =", twoDim.ndim) 
print("Dimension =", twoDim.shape)
print("Size =", twoDim.size) 
print("Array type =", twoDim.dtype)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
#Dimensions = 2
Dimension = (4, 2)
Size = 8
Array type = int32


In [8]:
arrFromTuple = np.array([(1,'a',3.0),(2,'b',3.5)])  # create ndarray from tuple
print(arrFromTuple) 
print("#Dimensions =", arrFromTuple.ndim) 
print("Dimension =", arrFromTuple.shape) 
print("Size =", arrFromTuple.size)
print("Array type =", arrFromTuple.dtype)

[['1' 'a' '3.0']
 ['2' 'b' '3.5']]
#Dimensions = 2
Dimension = (2, 3)
Size = 6
Array type = <U11


<U21 : little endian, Unicode

In [9]:
#Guess what is printed 
print(np.array([1]).shape)
print(np.array([1,2]).shape)
print(np.array([[1],[2]]).shape)
print(np.array([[[1,2,3],[1,2,3]]]).shape)
print(np.array([[[[]]]]).shape)

(1,)
(2,)
(2, 1)
(1, 2, 3)
(1, 1, 1, 0)


Python tuple
https://wiki.python.org/moin/TupleSyntax (https://wiki.python.org/moin/TupleSyntax)
Python tuple is defined by trailing comma, not by parenthesis 1, 1,2, 1,2,3, parenthesis is optional

In [10]:
(1,2) == (1,2,)

True

In [11]:
print(np.random.rand(5))      # random numbers from a uniform distribution between [0,1] 
print(np.random.randn(5))     # 정규분포random numbers from a normal distribution 
print(np.arange(-10,10,2))    # similar to range, but returns ndarray instead of list
print(np.arange(12).reshape(3,4))  # reshape to a matrix 
print(np.linspace(0,1,10))    # split interval [0,1] into 10 equally separated values
print(np.logspace(-3,3,7))    #log(10^-3, 10^2, 10^1 ...) create ndarray with values from 10^-3 to 10^3                              # logspace returns numbers spaced evenly on a log scale.

[0.24231084 0.70845095 0.72155839 0.46746147 0.49602413]
[ 0.80820269  1.4096213  -0.41006585 -0.73650395  0.71413253]
[-10  -8  -6  -4  -2   0   2   4   6   8]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[1.e-03 1.e-02 1.e-01 1.e+00 1.e+01 1.e+02 1.e+03]


In [12]:
print(np.zeros((2,3)))        # a matrix of zeros 
print(np.ones((3,2)))         # a matrix of ones 
print(np.eye(3))              # a 3 x 3 identity matrix

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Element-wise Operations 
You can apply standard operators such as addition and multiplication on each element of the ndarray

In [13]:
x = np.array([1,2,3,4,5])
print(x + 1)      # addition            #broad casting
print(x - 1)      # subtraction 
print(x * 2)      # multiplication 
print(x // 2)     # integer division 
print(x ** 2)     # square
print(x % 2)      # modulo  
print(1 / x)      # division

[2 3 4 5 6]
[0 1 2 3 4]
[ 2  4  6  8 10]
[0 1 1 2 2]
[ 1  4  9 16 25]
[1 0 1 0 1]
[1.         0.5        0.33333333 0.25       0.2       ]


In [14]:
x = np.array([2,4,6,8,10]) 
y = np.array([1,2,3,4,5])
print(x + y) 
print(x - y) 
print(x * y) 
print(x / y) 
print(x // y) 
print(x ** y)

[ 3  6  9 12 15]
[1 2 3 4 5]
[ 2  8 18 32 50]
[2. 2. 2. 2. 2.]
[2 2 2 2 2]
[     2     16    216   4096 100000]


# Indexing and Slicing 
There are various ways to select certain elements with an ndarray

In [15]:
x = np.arange(-5,5) 
print(x)

y = x[3:5]     # y is a slice, i.e., pointer to a subarray in x 
print(y) 
y[:] = 1000    # modifying the value of y will change x 
print(y,"y") 
print(x,"x")

z = x[3:5].copy()   # makes a copy of the subarray 
print(z,"z") 
z[:] = 500          # modifying the value of z will not affect x 
print(z) 
print(x)

[-5 -4 -3 -2 -1  0  1  2  3  4]
[-2 -1]
[1000 1000] y
[  -5   -4   -3 1000 1000    0    1    2    3    4] x
[1000 1000] z
[500 500]
[  -5   -4   -3 1000 1000    0    1    2    3    4]


**Remark: slicing a list makes a copy of the sublist, but slicing numpy array does not**

In [16]:
# Remark slicing a list makes a copy of the sublist 
x = list(range(-5,5))
print(x)

y = x[3:5]     # y is a slice, i.e., not a pointer to a list in x 
print(y) 
y[1] = 1000    # modifying the value of y does not change x 
print(y) 
print(x)

[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4]
[-2, -1]
[-2, 1000]
[-5, -4, -3, -2, -1, 0, 1, 2, 3, 4]


In [17]:
import numpy as np

def find_k_nearest_index(data, center, k=1):

# YOUR CODE MUST BE HERE
    dist=np.sqrt(np.sum(np.square(DmulD-D), axis=1))                #거리구하기
    key=np.partition(dist,k)[k-1]
    result=np.argwhere(dist<=key)[: ,0]
    print('array('+np.array2string(result,separator=', ')+')')


In [18]:
my2dlist = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]   # a 2-dim list 
print(my2dlist) 
print(my2dlist[2])        # access the third sublist 
print(my2dlist[2][:],"         my2dlist[:][2]\n")     # can't access third element of each sublist 
#print(my2dlist[:,2])    # this will cause syntax error

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
[9, 10, 11, 12]
[9, 10, 11, 12]          my2dlist[:][2]



In [19]:
my2darr = np.array(my2dlist) 
print(my2darr)
print("my2darr\n") 
print(my2darr[2][:])      # access the third row 
print("my2darr[2][:]\n")
print(my2darr[2,:])       #넘파이 다운 표현 access the third row 
print("my2darr[2,:]\n")
print(my2darr[:][2])      # access the third row (similar to 2d list); Don't do this 
print("my2darr[:][2]\n")
print(my2darr[:,2])       # access the third column 
print("my2darr[:,2]\n")
print(my2darr[:2,2:])     # access the first two rows & last two columns 
print("my2darr[:2,2:]\n")
print(my2darr[::2,2:])    # applying skippe
print("my2darr[::2,2:]\n")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
my2darr

[ 9 10 11 12]
my2darr[2][:]

[ 9 10 11 12]
my2darr[2,:]

[ 9 10 11 12]
my2darr[:][2]

[ 3  7 11]
my2darr[:,2]

[[3 4]
 [7 8]]
my2darr[:2,2:]

[[ 3  4]
 [11 12]]
my2darr[::2,2:]



In [20]:
my2darr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])   # a 2-dim list 
print(my2darr)

print() 
sliced = my2darr[::2,2:]   # applying skipper 
print(sliced,"sliced")    
print(type(sliced))

print() 
sliced[:,:] = 1000 
print(my2darr)

print() 
sliced[0,0] = 2000 
print(my2darr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 3  4]
 [11 12]] sliced
<class 'numpy.ndarray'>

[[   1    2 1000 1000]
 [   5    6    7    8]
 [   9   10 1000 1000]]

[[   1    2 2000 1000]
 [   5    6    7    8]
 [   9   10 1000 1000]]


### **ndarray also supports boolean indexing (also called masking).**

In [21]:
#slicing vs masking vs integer array indexing 
x = np.array([1,2,3]) 
print(x[1:])                    # slicing 
print(x[1:][0])                    # slicing

print() 
print(x[[True, False, True]],"here")   # boolean masking

print() 
print(x[[2,1]])                 # integer array indexing 
print(x[[2,1,1,1,0]])                 # integer array indexing

print() 
x[[2,1,1,1,0]] = 0 
print(x)

[2 3]
2

[1 3] here

[3 2]
[3 2 2 2 1]

[0 0 0]


In [22]:
y = np.arange(35).reshape(5,7) 
b = y > 20 
print(y,"y")
print(b,"b")

print() 
t = y[b]   # Filtering result is always one-dimensional; it's a copy; not indexing 
print(t) 

print() 
t[:3] = 1000 
print(t) 
print(y)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]] y
[[False False False False False False False]
 [False False False False False False False]
 [False False False False False False False]
 [ True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]] b

[21 22 23 24 25 26 27 28 29 30 31 32 33 34]

[1000 1000 1000   24   25   26   27   28   29   30   31   32   33   34]
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]]


**LAB**: set to zero if the value is a even number in 2-d arra

In [23]:
M = np.arange(35).reshape(5,7) 
M

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [24]:
M[M % 2 == 0] = 0 
M

array([[ 0,  1,  0,  3,  0,  5,  0],
       [ 7,  0,  9,  0, 11,  0, 13],
       [ 0, 15,  0, 17,  0, 19,  0],
       [21,  0, 23,  0, 25,  0, 27],
       [ 0, 29,  0, 31,  0, 33,  0]])

In [25]:
M[M % 2 == 0] = -M[M % 2 == 0] 
M

array([[ 0,  1,  0,  3,  0,  5,  0],
       [ 7,  0,  9,  0, 11,  0, 13],
       [ 0, 15,  0, 17,  0, 19,  0],
       [21,  0, 23,  0, 25,  0, 27],
       [ 0, 29,  0, 31,  0, 33,  0]])

In [26]:
my2darr = np.arange(1,13,1).reshape(4,3) 
print(my2darr)
print()

indices = [2,1,0,3]    # selected row indices \
print(my2darr[indices,:])
print()

rowIndex = [0,0,1,2,3]     # row index into my2darr 
columnIndex = [0,2,0,1,2]  # column index into my2darr
print(my2darr[rowIndex,columnIndex])  # element-wis
print()

print(my2darr[rowIndex,:])

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 7  8  9]
 [ 4  5  6]
 [ 1  2  3]
 [10 11 12]]

[ 1  3  4  8 12]

[[ 1  2  3]
 [ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# ^indexing 1.slicing 2.boolean* 3.integer

### Numpy Arithmetic and Statistical Functions
There are many built-in mathematical functions available for manipulating elements of nd-array

In [27]:
y = np.array([-1.4, 0.4, -3.2, 2.5, 3.4])    # generate a random vector 
print(y)
print()

print(np.abs(y))          # convert to absolute values 
print(np.sqrt(np.abs(y)))    # apply square root to each element 
print(np.sign(y))         # 음-1양1 get the sign of each element 
print(np.exp(y))          # e^data apply exponentiation: e^y 
print(np.sort(y))         # sort array; return a sorted copy of an array 
print(y)                  # y does not change

[-1.4  0.4 -3.2  2.5  3.4]

[1.4 0.4 3.2 2.5 3.4]
[1.18321596 0.63245553 1.78885438 1.58113883 1.84390889]
[-1.  1. -1.  1.  1.]
[ 0.24659696  1.4918247   0.0407622  12.18249396 29.96410005]
[-3.2 -1.4  0.4  2.5  3.4]
[-1.4  0.4 -3.2  2.5  3.4]


In [28]:
x = np.arange(-2,3) 
y = np.random.randn(5) 
print(x) 
print(y)
print()
print(np.add(x,y))           # element-wise addition       x + y 
print("np.add(x,y)")
print(np.subtract(x,y))      # element-wise subtraction    x - y 
print("np.subtract(x,y)")
print(np.multiply(x,y))      # element-wise multiplication x * y 
print("np.multiply(x,y)")
print(np.divide(x,y))        # element-wise division       x / y 
print("np.divide(x,y)")
print(np.maximum(x,y))       # element-wise maximum        max(x,y)
print("np.maximum(x,y)")

[-2 -1  0  1  2]
[-0.0275389  -0.93233994 -1.7394736  -0.39321441  0.47329646]

[-2.0275389  -1.93233994 -1.7394736   0.60678559  2.47329646]
np.add(x,y)
[-1.9724611  -0.06766006  1.7394736   1.39321441  1.52670354]
np.subtract(x,y)
[ 0.05507779  0.93233994 -0.         -0.39321441  0.94659292]
np.multiply(x,y)
[72.62455233  1.07257017 -0.         -2.54314182  4.22568128]
np.divide(x,y)
[-0.0275389  -0.93233994  0.          1.          2.        ]
np.maximum(x,y)


In [29]:
y = np.array([-3.2, -1.4, 0.4, 2.5, 3.4])    # generate a random vector 
print(y)
print("Min =", np.min(y))             # min 
print("Max =", np.max(y))             # max 
print("Average =", np.mean(y))        # mean/average 
print("Std deviation =", np.std(y))   # 표준 편차 standard deviation 
print("Sum =", np.sum(y))             # sum 

[-3.2 -1.4  0.4  2.5  3.4]
Min = -3.2
Max = 3.4
Average = 0.34000000000000014
Std deviation = 2.432776191925595
Sum = 1.7000000000000006


### More on filtering

In [30]:
M = np.arange(25).reshape(5,5) 
print(M) 
print(M[M%2==1])                        # filtering in general 
print(np.argwhere(M >= 20),"here")
print("arg")# indexes satisfying condition 
print(np.where(M % 2 == 1, M, 0))       # M, 0 is broadcas

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[ 1  3  5  7  9 11 13 15 17 19 21 23]
[[4 0]
 [4 1]
 [4 2]
 [4 3]
 [4 4]] here
arg
[[ 0  1  0  3  0]
 [ 5  0  7  0  9]
 [ 0 11  0 13  0]
 [15  0 17  0 19]
 [ 0 21  0 23  0]]


# New axis 
       Used to increase the dimension of the existing array by one more dimension 
       shape change, for example: n x (newaxis) x m  n x 1 x 

In [31]:
t = np.array([1,2,3]) 
print(t.shape) 
print(t)
print()

x = t[:, np.newaxis] 
print(x.shape) 
print(x)
print()

y = t[np.newaxis, :] 
print(y.shape)
print(y)
print()

(3,)
[1 2 3]

(3, 1)
[[1]
 [2]
 [3]]

(1, 3)
[[1 2 3]]



**x and y are broadcasted** (it is explained below)

In [32]:
x + y

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [33]:
t = np.array([[1,2,3],[4,5,6]])
print(t)
print(t.shape)
print("t\n")

print(t[:, :, np.newaxis].shape) 
print(t[:, :, np.newaxis]) 
print()

print(t[np.newaxis, :, :].shape) 
print(t[np.newaxis, :, :])

print() 
print(t[:, np.newaxis, :].shape)
print(t[:, np.newaxis, :])

[[1 2 3]
 [4 5 6]]
(2, 3)
t

(2, 3, 1)
[[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]

(1, 2, 3)
[[[1 2 3]
  [4 5 6]]]

(2, 1, 3)
[[[1 2 3]]

 [[4 5 6]]]


# Broadcasting 
Broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, the smaller array is “broadcast” across the larger array so that they have compatible shapes.

Examples:

    A      (2d array):  5 x 4 
    B      (1d array):      1 
    Result (2d array):  5 x 4 

    A      (2d array):  5 x 4 
    B      (1d array):      4 
    Result (2d array):  5 x 4 

    A      (3d array):  15 x 3 x 5 
    B      (3d array):  15 x 1 x 5 
    Result (3d array):  15 x 3 x 5 

    A      (3d array):  15 x 3 x 5 
    B      (2d array):       3 x 5 
    Result (3d array):  15 x 3 x 5 

    A      (3d array):  15 x 3 x 5 
    B      (2d array):       3 x 1 
    Result (3d array):  15 x 3 x 5

In [34]:
np.array([[1,2],[3,4]]) + np.array([[10]])

array([[11, 12],
       [13, 14]])

In [35]:
np.array([[1,2],[3,4]]) + np.array([[10,100]])

array([[ 11, 102],
       [ 13, 104]])

In [36]:
A = np.array([[1,2]]) 
B = np.array([[10],[100]]) 
print(A)
print(B)
print(A.shape, B.shape) 
C = A + B 
C

[[1 2]]
[[ 10]
 [100]]
(1, 2) (2, 1)


array([[ 11,  12],
       [101, 102]])

In [37]:
X = np.array([[1]]*3) + np.array([[0]*10]) 
X

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [38]:
a= np.array([[1]]*3)
b=np.array([[0]*10]) 
print(a)
print(b)

[[1]
 [1]
 [1]]
[[0 0 0 0 0 0 0 0 0 0]]


In [39]:
a = np.array([[1],[2],[3]]) 
print(a.shape)
b = a.T # matrix를 행과 열 전환
print(b)
a + b

(3, 1)
[[1 2 3]]


array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

# Meshgrid
Make D x N mesh grid for vectorized evaluations


In [40]:
v = np.array([10,20,30])   # N 
w = np.array([5,6])        # D 
print(v)
print(w)
print( )

X, Y = np.meshgrid(v, w) 
print(X)
print()
print(Y)

print()
X + Y

[10 20 30]
[5 6]

[[10 20 30]
 [10 20 30]]

[[5 5 5]
 [6 6 6]]



array([[15, 25, 35],
       [16, 26, 36]])

In [41]:
v+w[:,np.newaxis]

array([[15, 25, 35],
       [16, 26, 36]])

# Axis ordering 
- By definition, the axis number of the dimension is the index of that dimension within the array's shape. It is also the position used to access that dimension during indexing. 
- For example, if a 2D array a has shape (5,6), then you can access a[0,0] up to a[4,5]. Axis 0 is thus the first dimension (the "rows"), and axis 1 is the second dimension (the "columns"). In higher dimensions, where "row" and "column" stop really making sense, try to think of the axes in terms of the shapes and indices involved. 
- If you do np.sum(axis=n), for example, then dimension n is collapsed and deleted, with each value in the new matrix equal to the sum of the corresponding collapsed values. For example, if b has shape (5,6,7,8), and you do c = b.sum(axis=2), then axis 2 (dimension with size 7) is collapsed, and the result has shape (5,6,8). Furthermore, c[x,y,z] is equal to the sum of all elements b[x,y,:,z].

In [42]:
X = np.array([[0,0,0], [1,1,1]]) 
X.shape

# axis 0 is row; axis 1 is column


(2, 3)

In [43]:
X.sum(axis=0)   # dimension 0 is collapsed and deleted; or aggregated over dimension 0

array([1, 1, 1])

In [44]:
X.sum(axis=1)   # dimension 1 is collapsed and deleted; or aggregated over dimension 0

array([0, 3])

In [45]:
X = np.array(range(1,24+1)).reshape(2,3,4)

In [46]:
print(X)
X.shape

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


(2, 3, 4)

In [47]:
X.sum(axis=0)

array([[14, 16, 18, 20],
       [22, 24, 26, 28],
       [30, 32, 34, 36]])

In [48]:
X.sum(axis=1)

array([[15, 18, 21, 24],
       [51, 54, 57, 60]])

In [49]:
X.sum(axis=2)

array([[10, 26, 42],
       [58, 74, 90]])

In [50]:
X.sum(axis=(1,2))

array([ 78, 222])

In [51]:
X.sum(axis=(0,1,2))

300

In [52]:
import numpy as np
X = np.array(np.arange(2*3, 0, -1).reshape(2,3)) 
print(X)
print() 
print("axis=0\n", np.sort(X, axis=0)) 
print()
print("axis=-1\n", np.sort(X, axis=-1)) 
print() 
print("default is -1\n", np.sort(X)) 
print()
print("axis=None\n", np.sort(X, axis=None))   

[[6 5 4]
 [3 2 1]]

axis=0
 [[3 2 1]
 [6 5 4]]

axis=-1
 [[4 5 6]
 [1 2 3]]

default is -1
 [[4 5 6]
 [1 2 3]]

axis=None
 [1 2 3 4 5 6]


# sort vs argsort vs partition vs argpartition 
- argmin, argmax, ...

In [53]:
X = np.array([3,3,3,4,4,4,4,4]) 
print('X =\n', X) 
print('sorted =\n', np.sort(X)) 
print('argsorted =\n', np.argsort(X)) 
print('partitioned first 3 =\n', np.partition(X, 3)) # 기준으러 작은데 큰데
print('argpartitioned first 3 =\n', np.argpartition(X, 3)) 
print('partitioned last 3=\n', np.partition(X, -3)) 
print('argpartitioned last 3=\n', np.argpartition(X, -3))

X =
 [3 3 3 4 4 4 4 4]
sorted =
 [3 3 3 4 4 4 4 4]
argsorted =
 [0 1 2 3 4 5 6 7]
partitioned first 3 =
 [3 3 3 4 4 4 4 4]
argpartitioned first 3 =
 [0 1 2 6 3 5 4 7]
partitioned last 3=
 [4 3 3 3 4 4 4 4]
argpartitioned last 3=
 [6 0 2 1 3 5 4 7]


**LAB**

sort 2-d array T along axis 0, sort key is the sum of elements along axis 1

In [54]:
T = np.array([[2,2],[-1,10],[0,1]]) 
print(T)
print()
print(np.sum(T, axis=1))
print()
print(np.argsort(T),"d")
I = np.argsort(np.sum(T, axis=1)) 
print(I)
T[I,:]

[[ 2  2]
 [-1 10]
 [ 0  1]]

[4 9 1]

[[0 1]
 [0 1]
 [0 1]] d
[2 0 1]


array([[ 0,  1],
       [ 2,  2],
       [-1, 10]])

# Vectorized function 
- similar to map functio

In [55]:
import numpy as np

In [56]:
X = np.array([[1, 2], [1, 4], [1, 0],
              [10, 2], [10, 4], [10, 0]])

In [57]:
cluster_centers_=np.array([[10.,  0.], [ 1. , 4.], [10.,  2.]])

In [58]:
X-cluster_centers_[0]

array([[-9.,  2.],
       [-9.,  4.],
       [-9.,  0.],
       [ 0.,  2.],
       [ 0.,  4.],
       [ 0.,  0.]])

In [59]:
(X-cluster_centers_[0])**2

array([[81.,  4.],
       [81., 16.],
       [81.,  0.],
       [ 0.,  4.],
       [ 0., 16.],
       [ 0.,  0.]])

In [60]:
np.sqrt(np.sum((X-cluster_centers_[0])**2,axis=1))

array([9.21954446, 9.8488578 , 9.        , 2.        , 4.        ,
       0.        ])

In [61]:
min(range(3),key=lambda i: np.sqrt(np.sum((X-cluster_centers_[i])**2)))

2

In [62]:
u = np.array([1,2]) 
v = np.array([[1,2],[2,3]]) 
w = np.array([4,3,2,1]) 
np.vectorize(max)(*w)    # map 이랑 유사 세개에서 max값 넣는다

array(4)

In [63]:
dist = np.vectorize(lambda x, y : (x**2+y**2))
dist(*v)

array([ 5, 13])

In [64]:
w

array([4, 3, 2, 1])

# Numpy linear algebra
Numpy provides many functions to support linear algebra operations.

In [65]:
X

array([[ 1,  2],
       [ 1,  4],
       [ 1,  0],
       [10,  2],
       [10,  4],
       [10,  0]])

In [66]:
Y

array([[5, 5, 5],
       [6, 6, 6]])

In [67]:
np.dot(X,X.T)

array([[  5,   9,   1,  14,  18,  10],
       [  9,  17,   1,  18,  26,  10],
       [  1,   1,   1,  10,  10,  10],
       [ 14,  18,  10, 104, 108, 100],
       [ 18,  26,  10, 108, 116, 100],
       [ 10,  10,  10, 100, 100, 100]])

In [68]:
X = np.random.randn(2,3)
print("\nX",X.shape)#matrix
print(X)            
print("\nX.T")
print(X.T)
y = np.random.randn(3) # vector
print("\ny")
print(y)
print("\nX.dot(y)")
print(X.dot(y))          #내적 inner product     -> scalar
print("\nnp.dot(X,y)")
print(np.dot(X,y))
print("\nX.dot(X.T)")
print(X.dot(X.T))
print("\nX.T.dot(X)")
print(X.T.dot(X))


X (2, 3)
[[-1.37649253 -0.39800608  0.36720687]
 [ 0.88685578 -0.19925894  0.40411512]]

X.T
[[-1.37649253  0.88685578]
 [-0.39800608 -0.19925894]
 [ 0.36720687  0.40411512]]

y
[0.48129223 1.00895876 0.67315923]

X.dot(y)
[-0.81687818  0.49782656]

np.dot(X,y)
[-0.81687818  0.49782656]

X.dot(X.T)
[[ 2.18798141 -0.99305024]
 [-0.99305024  0.98952632]]

X.T.dot(X)
[[ 2.68124485  0.37113846 -0.14706568]
 [ 0.37113846  0.19811296 -0.22667412]
 [-0.14706568 -0.22667412  0.29814991]]


In [69]:
X = np.random.randn(5,3)
print(X)
print()
C=X.T.dot(X) #   I idetity matrix
print(C,"I")
print()
invC = np.linalg.inv(C)  # 역행렬
print(invC,"invC")
print()
detC = np.linalg.det(C)  # 판별식
print(detC)
print()
S, U = np.linalg.eig(C) #eigen value
print(S,"S")
print()
print(U)


[[ 1.83027917 -0.71369962 -0.14521123]
 [-0.38175366  0.07115753 -0.82119573]
 [ 1.25075574  0.08164382 -0.32719357]
 [-0.2579667  -1.12222592  0.70233743]
 [ 0.40312469  2.06074082  0.88956465]]

[[ 5.28910397 -0.11108531 -0.18409604]
 [-0.11108531  6.02714001  1.06347052]
 [-0.18409604  1.06347052  2.08710749]] I

[[ 0.18965216  0.00059747  0.01642408]
 [ 0.00059747  0.18230877 -0.09284141]
 [ 0.01642408 -0.09284141  0.52788739]] invC

60.364826096255044

[5.27290413 6.31864906 1.81179828] S

[[-0.98810109 -0.14751838  0.04352667]
 [-0.15369675  0.95769372 -0.24331058]
 [ 0.00579244  0.24710536  0.96897131]]


# The Frobenius norm

https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.norm.html 
(https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.norm.html)

In [70]:
X =np.array([1,2])
print(np.linalg.norm(X))                 #그냥 길이, 유클리드
print(np.linalg.norm(X,ord=1)  )          #city distacne 맨한탄 거리
print(np.linalg.norm(X,ord=np.inf))        # 무한
print(np.linalg.norm(X,ord= -np.inf))        # -무한

2.23606797749979
3.0
2.0
1.0


# 시험에 낼거야
# https://proofwiki.org/wiki/Cosine_Formula_for_Dot_Product
# 코사인


In [71]:
import math
x = np.array([1,0])
y = np.array([0,1])
print("cosine =", x.dot(y) / (math.sqrt((x.dot(x))) * math.sqrt((y.dot(y))))) 
print("cosine =", x.dot(y) / (np.linalg.norm(x) * np.linalg.norm(y)))

cosine = 0.0
cosine = 0.0


# LAB: distance matrix

**In case of 1-d points**

In [72]:
pts = np.array([1.,2,3,4,5])
print(pts)
u = pts[:,np.newaxis]
print(u)
v = pts.T[np.newaxis, :]
print(v)
np.abs(u-v)

[1. 2. 3. 4. 5.]
[[1.]
 [2.]
 [3.]
 [4.]
 [5.]]
[[1. 2. 3. 4. 5.]]


array([[0., 1., 2., 3., 4.],
       [1., 0., 1., 2., 3.],
       [2., 1., 0., 1., 2.],
       [3., 2., 1., 0., 1.],
       [4., 3., 2., 1., 0.]])

In [73]:
print(pts.shape)
pts

(5,)


array([1., 2., 3., 4., 5.])

In [74]:
print(u.shape)
u

(5, 1)


array([[1.],
       [2.],
       [3.],
       [4.],
       [5.]])

In [75]:
print(v.shape)
v

(1, 5)


array([[1., 2., 3., 4., 5.]])

**In case of n-d points**

In [76]:
np.dot(X,Y)

array([17, 17, 17])

In [77]:
pts = np.array([[1,0],[1,1],[0,1]])
print(pts.shape)
print(pts)
u = pts[:,:,np.newaxis]
v = pts.T[np.newaxis]

(3, 2)
[[1 0]
 [1 1]
 [0 1]]


In [78]:
print(v.shape)
print(u.shape)

(1, 2, 3)
(3, 2, 1)


In [79]:
np.sqrt(np.sum((u-v)**2, axis=1))

array([[0.        , 1.        , 1.41421356],
       [1.        , 0.        , 1.        ],
       [1.41421356, 1.        , 0.        ]])

In [80]:
np.linalg.norm(u-v,axis=1)

array([[0.        , 1.        , 1.41421356],
       [1.        , 0.        , 1.        ],
       [1.41421356, 1.        , 0.        ]])

- In your real application, use sklearn.metrics.pairwise to compute pairwise distances

In [81]:
from sklearn.metrics.pairwise import euclidean_distances, manhattan_distances,cosine_similarity

print(euclidean_distances(pts))
print(manhattan_distances(pts))
print(cosine_similarity(pts))

[[0.         1.         1.41421356]
 [1.         0.         1.        ]
 [1.41421356 1.         0.        ]]
[[0. 1. 2.]
 [1. 0. 1.]
 [2. 1. 0.]]
[[1.         0.70710678 0.        ]
 [0.70710678 1.         0.70710678]
 [0.         0.70710678 1.        ]]


- If you define your own distance

In [82]:
u_dist = lambda x,y : np.sum(np.abs(np.subtract(x,y)))


In [83]:
from sklearn.metrics.pairwise import pairwise_distances

inf_dist = lambda x, y : np.max(np.abs(x-y))
print(pairwise_distances(pts, metric = inf_dist))

[[0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 0.]]


In [84]:
pts

array([[1, 0],
       [1, 1],
       [0, 1]])

In [85]:
pairwise_distances(pts,metric = u_dist )

array([[0., 1., 2.],
       [1., 0., 1.],
       [2., 1., 0.]])

In [92]:
np.abs(x-y)

array([1, 1])